### ISSUE TITLE
unique id will change after re-installed, or reset-device

### ISSUE THREAD

**Issue by fukemy** [cesarferreira/android-unique-device-id#2]
using sharedpreference to store device UUID is very bad solution

**Comment by cesarferreira** [comment]
![image](https://user-images.githubusercontent.com/277426/108922406-038c5100-762f-11eb-8e4d-11449c529e72.png)


That's exactly the purpose of the library, it's a random ID that only lasts until either you have the app uninstalled or fully wiped, it identifies an "installation".
